Integrate project harfbuzz with target hb-subset-fuzzer
google/fuzzbench pull request #871
Opened 2020-10-26 16:25 UTC by Vaush

2020-10-26 19:08 UTC, inferno-chromium requested changes

2020-10-26 19:08 UTC, inferno-chromium commented on benchmarks/harfbuzz_hb-subset-fuzzer/hb-draw-fuzzer.options
> +timeout = 5
Remove all other option files other than subset fuzzer.

2020-10-26 19:08 UTC, inferno-chromium commented on benchmarks/harfbuzz_hb-subset-fuzzer/build.sh
> +mv $build/test/fuzzing/hb-{shape,draw,subset,set}-fuzzer $OUT/
remove everything other than subset fuzzer in this build.sh files.

2020-10-26 19:18 UTC, jonathanmetzman commented
I think you need to blocklist klee.

2020-10-27 01:49 UTC, Vaush commented
> 
> 
> I think you need to blocklist klee.

I will blocklist it, but apparently the problem is that klee doesn't support emtpy seeds (at least, that's what the error says). Still, I don't think deleting part of the corpus would be a good idea.

2020-10-27 03:45 UTC, inferno-chromium approved these changes

2020-10-27 03:45 UTC, merged